before_script:
  - make clean

after_script:
  - make clean

stages:
  - build
  - test

build:
  stage: build
  script:
    - make check
    - make build

test:
  stage: test
  script:
    - make test

