before_script:
  - make clean

after_script:
  - make clean

stages:
  - check
  - build
  - test

check:
  stage: check
  script:
    - make check

build:
  stage: build
  script:
    - make build
    - make package
    - make assembly

test:
  stage: test
  script:
    - make test

