name: Codecov

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-java@v10
        with:
          java-version: 11
      - run: sbt clean coverage test coverageReport && sbt coverageAggregate
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          name: codecov-alephium
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
