name: Integration-Test

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  itest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        java: [ '1.8', '11' ]
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.java }}
      - run: sbt it:test
        shell: bash
