name: Styling

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  styling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-java@v10
        with:
          java-version: 11
      - run: sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck it:scalafmtCheck scalastyle test:scalastyle it:scalastyle doc
      - run: make assembly
